version: '3'
services:
  magic:
    image: mageai/mageai:latest
    container_name: mageai
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

      TARGETED_POSTGRES_DBNAME: ${TARGETED_POSTGRES_DBNAME}
      TARGETED_POSTGRES_USER: ${TARGETED_POSTGRES_USER}
      TARGETED_POSTGRES_PASSWORD: ${TARGETED_POSTGRES_PASSWORD}
      TARGETED_POSTGRES_HOST: ${TARGETED_POSTGRES_HOST}
      TARGETED_POSTGRES_PORT: ${TARGETED_POSTGRES_PORT}

    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - /Users/user/.google/cdq/dezoomcamp-2024.json:/home/src/dezoomcamp-2024.json
    restart: on-failure:5
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: mage_postgresdb_14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
