version: 2

sources:
  - name: staging
    database: radiant-gateway-412001
    schema: all_trips_data
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_2019_tripdata

models:
    - name: stg_green_tripdata
      description: >
        Trip made by green taxis, also known as boro taxis and street-hail liveries.
        Green taxis may respond to street hails,but only in the areas indicated in green on the
        map (i.e. above W 110 St/E 96th St in Manhattan and in the boroughs).
        The records were collected and provided to the NYC Taxi and Limousine Commission (TLC) by
        technology service providers. 
      
      columns:
        - name: tripid
          data_type: string
          description: ""
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn

        - name: vendorid
          data_type: int64
          description: ""

        - name: ratecodeid
          data_type: int64
          description: ""

        - name: pickup_locationid
          data_type: int64
          description: locationid where the meter was engaged.
          tests:
            - relationships:
                to: ref('taxi_zone_lookup')
                field: locationid
                severity: warn

        - name: dropoff_locationid
          data_type: int64
          description: locationid where the meter was engaged.
          tests:
            - relationships:
                to: ref('taxi_zone_lookup')
                field: locationid
                severity: warn

        - name: pickup_datetime
          data_type: timestamp
          description: ""

        - name: dropoff_datetime
          data_type: timestamp
          description: ""

        - name: store_and_fwd_flag
          data_type: string
          description: ""

        - name: passenger_count
          data_type: int64
          description: ""

        - name: trip_distance
          data_type: numeric
          description: ""

        - name: trip_type
          data_type: int64
          description: ""

        - name: fare_amount
          data_type: numeric
          description: ""

        - name: extra
          data_type: numeric
          description: ""

        - name: mta_tax
          data_type: numeric
          description: ""

        - name: tip_amount
          data_type: numeric
          description: ""

        - name: tolls_amount
          data_type: numeric
          description: ""

        - name: ehail_fee
          data_type: numeric
          description: ""

        - name: improvement_surcharge
          data_type: numeric
          description: ""

        - name: total_amount
          data_type: numeric
          description: ""

        - name: payment_type
          data_type: int64
          description: ""
          tests:
            - accepted_values:
                values: "{{ var('payment_type_values') }}"
                severity: warn
                quote: false

        - name: payment_type_description
          data_type: string
          description: ""
    - name: stg_yellow_tripdata
      description: > 
        Trips made by New York City's iconic yellow taxis. 
        Yellow taxis are the only vehicles permitted to respond to a street hail from a passenger in all five
        boroughs. They may also be hailed using an e-hail app like Curb or Arro.
        The records were collected and provided to the NYC Taxi and Limousine Commission (TLC) by
        technology service providers. 
      
      columns:
        - name: tripid
          data_type: string
          description: ""
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn

        - name: vendorid
          data_type: int64
          description: ""

        - name: ratecodeid
          data_type: int64
          description: ""

        - name: pickup_locationid
          data_type: int64
          description: ""
          tests:
            - relationships:
                to: ref('taxi_zone_lookup')
                field: locationid
                severity: warn

        - name: dropoff_locationid
          data_type: int64
          description: ""
          tests:
            - relationships:
                to: ref('taxi_zone_lookup')
                field: locationid
                severity: warn

        - name: pickup_datetime
          data_type: timestamp
          description: ""

        - name: dropoff_datetime
          data_type: timestamp
          description: ""

        - name: store_and_fwd_flag
          data_type: string
          description: ""

        - name: passenger_count
          data_type: int64
          description: ""

        - name: trip_distance
          data_type: numeric
          description: ""

        - name: trip_type
          data_type: numeric
          description: ""

        - name: fare_amount
          data_type: numeric
          description: ""

        - name: extra
          data_type: numeric
          description: ""

        - name: mta_tax
          data_type: numeric
          description: ""

        - name: tip_amount
          data_type: numeric
          description: ""

        - name: tolls_amount
          data_type: numeric
          description: ""

        - name: ehail_fee
          data_type: numeric
          description: ""

        - name: improvement_surcharge
          data_type: numeric
          description: ""

        - name: total_amount
          data_type: numeric
          description: ""

        - name: payment_type
          data_type: int64
          description: ""
          tests:
            - accepted_values:
                values: "{{ var('payment_type_values') }}"
                severity: warn
                quote: false

        - name: payment_type_description
          data_type: string
          description: ""